### PR TITLE
fix incorrect markdown format

### PR DESCRIPTION
**Pull request by cosmicshuai**
closes: #6 
fix the syntax error in Line 3

### CODE REVIEW

**Comment by feich-ms** [comment]
Please resolve the build failure @cosmicshuai

**Comment by cosmicshuai** [comment]
@feich-ms now all CIs are passed.

**Comment by feich-ms** [comment]
Looks good to me, please merge it @cosmicshuai

**Comment by cosmicshuai** [comment]
@feich-ms now it is shiped

**Pull request merged**
